name: Deploy Java App to Amazon EC2

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Rama a desplegar'
        required: true
        default: 'develop'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}

      - name: Setup on jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: microsoft
          java-version: '21'
          cache: 'gradle'

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle and Shadowjar
        run: ./gradlew clean shadowjar

      - name: Print generated JAR path
        run: find build/libs -name "*.jar" -print

      - name: Move JAR to root for SCP
        id: move_jar
        run: |
          JAR_FULL_PATH=$(find build/libs -name "*.jar" | head -n 1)
          if [ -z "$JAR_FULL_PATH" ]; then
            echo "No se encontró JAR en build/libs"
            exit 1
          fi
          JAR_FILENAME=$(basename "$JAR_FULL_PATH")
          mv "$JAR_FULL_PATH" "$JAR_FILENAME"
          echo "moved_jar_filename=$JAR_FILENAME" >> $GITHUB_OUTPUT

      - name: Validate SSH key secret exists
        run: |
          if [ -z "${{ secrets.EC2_SSH_PRIVATE_KEY }}" ]; then
            echo "El secret EC2_SSH_PRIVATE_KEY no está configurado"
            exit 1
          fi

      - name: Start ssh-agent and add key (webfactory)
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Add host to known_hosts
        run: |
          # Añadimos el host para evitar prompts cuando SSH se conecta por primera vez
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}

      - name: Execute pre-deployment script on EC2 (Stop old app)
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=yes ${EC2_USER}@${EC2_HOST} 'sudo -E /opt/apps/backend/scripts/pre-deploy'
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}

      - name: Copy JAR to EC2
        run: |
          scp -o BatchMode=yes -o StrictHostKeyChecking=yes "${{ steps.move_jar.outputs.moved_jar_filename }}" ${EC2_USER}@${EC2_HOST}:/opt/apps/backend/
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}

      - name: Execute post-deployment script on EC2 (Restart app and configure systemd)
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=yes ${EC2_USER}@${EC2_HOST} 'sudo -E /opt/apps/backend/scripts/post-deploy'
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}